### PR TITLE
Update to release 1.0.0

### PR DESCRIPTION
**Pull request by wendigo**

### CODE REVIEW

**Comment by wendigo** [comment]
cc @gnodet @ctamas

**Comment by cstamas** [comment]
LGTM, but let's wait for announce...

**Comment by wendigo** [comment]
@cstamas sure :)

**Comment by wendigo** [comment]
@cstamas up :)

**Comment by wendigo** [comment]
Checksums taken from:

- https://downloads.apache.org/maven/mvnd/1.0.0/maven-mvnd-1.0.0-linux-amd64.zip.sha256
- https://downloads.apache.org/maven/mvnd/1.0.0/maven-mvnd-1.0.0-darwin-aarch64.zip.sha256
- https://downloads.apache.org/maven/mvnd/1.0.0/maven-mvnd-1.0.0-darwin-amd64.zip.sha256

**Comment by wendigo** [comment]
Thanks @gnodet !

**Pull request merged**
